substitutions:
  node_name: midea-ac
  node_id: midea_ac
  friendly_node_name: "Midea AC"

esphome:
  name: ${node_name}
  comment: ${friendly_node_name}
  platform: ESP8266
  board: esp12e
  name_add_mac_suffix: true
  project:
    name: "lizardsystems.midea_mini_dongle"
    version: "1.4.0"

wifi:
  ap: {}


captive_portal:

logger:
  baud_rate: 0
  level: ERROR
  esp8266_store_log_strings_in_flash: false

ota:

web_server:
  port: 80

api:

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

midea_dongle:
  strength_icon: true
  
climate:
  - platform: midea_ac
    name: ${friendly_node_name} Climate
    id: ${node_id}_climate
    visual:
      min_temperature: 17 °C
      max_temperature: 30 °C
      temperature_step: 0.5 °C
    beeper: true
    preset_eco: true
    preset_sleep: true
    preset_boost: true
    custom_presets:
      - FREEZE_PROTECTION
    power_usage:
      name: "${friendly_node_name} Power Usage"
      id: ${node_id}_power_usage
    outdoor_temperature:
      name: "${friendly_node_name} Outdoor Temperature"
      id: ${node_id}_outdoor_temperature

